services:
  all-spark-notebook:
    build:
      context: .
    network_mode: host
    ports:
      - '0.0.0.0:4040:4040'
      - '0.0.0.0:8888:8888'
    volumes:
      - '.:/home/jovyan/work'
  neo4j:
    environment:
      NEO4J_AUTH: none
    image: 'neo4j:4.2.1'
    network_mode: host
    ports:
      - '0.0.0.0:7474:7474'
      - '0.0.0.0:7687:7687'
    volumes:
      - './data:/var/lib/neo4j/import'
      - '/tmp/neo4j/data:/data'
version: '3.3'
